baseurl = "https://npatta01.github.io/"
title = "My Blog"
languageCode = "en-us"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
googleAnalytics = "UA-47268287-3"

# Languages

defaultContentLanguage = "en"

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
  [[languages.en.menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3
  [[languages.en.menu.main]]
    url = "/presentations/"
    name = "Presentation"
    weight = 4
  [[languages.en.menu.main]]
    url = "https://npatta01.github.io/notes/"
    name = "Notes"
    weight = 5

# Links format

[permalinks]
  post = "/post/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Nidhin Pattaniyil"

  # Date format (default: Jan 2, 2006)
  # date_format = "Jan 2, 2006"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    # showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5

#pygmentsUseClasses = true
#
#PygmentsCodeFences = true
#PygmentsStyle = "monokai"
#pygmentsuseclasses = false
#pygmentsStyle= "monokai"
#pygmentsUseClassic=true
#PygmentesStyle = "friendly"

#pygmentsCodefences = true
#pygmentsCodefencesGuessSyntax = true
#
#[pygmentsOptions]
#    linenos = true
#    linenostart = 5